### ISSUE TITLE
Rumble test at main MiSTer menu

### ISSUE THREAD

**Issue by tjanas** [MiSTer-devel/MkDocs_MiSTer#10]
Pressing X or Y buttons at the main MiSTer screen will rumble the controller if supported. Not sure if this functionality is transient or will be a permanent feature, but I thought it would be nice to be documented as it was nice to discover.

**Comment by sorgelig** [comment]
actually it was supposed to be a test while tweaking rumble but i've forgot to remove it from release. So it's not decided yet as a permanent feature because X/Y are still used in OSD navigation.

**Comment by birdybro** [comment]
I wasn't even aware that this was a feature! (☉̃ₒ☉) I won't add it in for now for the reasons Sorgelig mentioned however.

**Comment by birdybro** [comment]
Since it's been awhile and the test is very useful for users, I've added it for now until further notice.
