### ISSUE TITLE
Implement Blogging feature

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/MkDocs_MiSTer#15]
I'm waiting on [the blog feature to be added to main branch](https://github.com/squidfunk/mkdocs-material/issues/3353) of Material for MkDocs first. I have added the Giscus app in preparation for the blog feature and will extend the theme for just the blog portion to allow comments that utilize github discussions when everything is ready.

The blogging feature will be used for core updates or feature articles to aid with SEO visibility of this extra information, without using documentation space to do so. Example of the Material for MkDocs blogging feature for reference:

https://squidfunk.github.io/mkdocs-material/blog/

And how it currently is accomplished I think is still behind closed doors, but you can see the Giscus comments snippet at the top here --> https://github.com/squidfunk/mkdocs-material/blob/master/src/overrides/blog.html

Example of the landing page with the previously mentioned overrides --> https://github.com/squidfunk/mkdocs-material/blob/master/docs/blog/index.md?plain=1

Apparently another override for the theme itself? I don't believe this one would be necessary to replicate --> https://github.com/squidfunk/mkdocs-material/blob/master/material/overrides/blog.html

Just a brainstorm for myself to reference later when the feature becomes officially available.

**Comment by sorgelig** [comment]
Github is not a general discussion place. There is already MiSTer forum which provides enough resources for discussions. Also there is a blog-like updates thread if someone wants to get centralized info about updates.
MkDocs should remain a Wiki without intention to replace the forum!

**Comment by birdybro** [comment]
There's no intention to replace the forum.

https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/

This is an example. 

I won't add anything like this without your approval, I'm leaving the references here for potential future use.

**Comment by birdybro** [comment]
Nevermind, I'll scrap the idea. You have a clear goal in mind for MkDocs.
