### ISSUE TITLE
Accessibility issue with color contrast

### ISSUE THREAD

**Issue by asturur** [MiSTer-devel/MkDocs_MiSTer#20]
I was browsing the docs and i noticed that some color combination play very hard on the eye
In this case i was searching on the search bar and the dropdown with results look like this

<img width="740" alt="image" src="https://user-images.githubusercontent.com/1194048/175951943-9d7a1cd8-2cc3-404d-9e1f-0bccb1e2e233.png">

Is very hard to read `hdmi pixel` when highlighted from the searc theme.
Please consider an higher contrast solution

**Comment by birdybro** [comment]
Thanks for the feedback! This specifically means I probably need to make another exception for the colors in the search drop-down. Putting the two situations side-by-side shows the source of the problem I believe. I'll look into it!

![image](https://user-images.githubusercontent.com/16388068/176016728-f5485b10-b5c0-4358-8550-aa7e476dd8a3.png)

**Comment by asturur** [comment]
To be clear, you don't have to point at 100% accessibility, it is nice if you do to warrant a reading experience that is ok for everyone ( some people could not be able to read it ).

So the dracula theme

![image](https://user-images.githubusercontent.com/1194048/176028179-e434fd3c-72f6-4c94-8247-8a8bfeb02ef6.png)

Seems to use the purple for code comments, things that are meant to don't disturb compared to code.
While for code is a color party.

It looks like that even the current light purple text, while is decently readable for me, isn't great either:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1194048/176029437-c8e6184e-90c0-48e4-bdaa-4536710301d4.png">

If you don't find a combination of colors you like to change the dark purple, you can also change type of effect, instead of a different color you can add underline to hovered links.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/1194048/176029745-b247465e-99d4-4053-baaf-08e2593a0d72.png">

It seems that in the website of the dracula theme, to contrast with the background they use those 2 colors that you can see in visual studio and sublime writings

**Comment by birdybro** [comment]
Yeah, part of the difficulty is that [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) uses a different color for the search box. It seems to be using the md-default-bg-color for the search box background which is #44475a.

![image](https://user-images.githubusercontent.com/16388068/176032163-9c5230f7-c1dc-4a89-8166-b595c2065c9a.png)

That is supposed to be the selection/current line value equivalent to dracula. I'm testing a bunch with some combinations, I'm missing some variable probably in the stylesheet. I'll also potentially change the typeset-a and accent-fg colors (which is the before and after highlight for link) to something more appropriate that meets the standards laid out in that contrast checker. I care a lot about accessibility in a general sense, so thanks for bringing that up.

**Comment by asturur** [comment]
definetely seems readable

**Comment by birdybro** [comment]
It should be all updated. Let me know if you notice anything else that needs improving regarding accessibility. :)

**Comment by birdybro** [comment]
Closing issue as it seems resolved, but if you notice any other accessibility issues feel free to re-open the issue.
