### ISSUE TITLE
Add info about wildcard functionality for core override settings

### ISSUE THREAD

**Issue by tjanas** [MiSTer-devel/MkDocs_MiSTer#3]
It should be noted in the documentation that the _corename_ in MiSTer.ini can support wildcards. Example:
`[dkong*] ; for all cores with a CORENAME that begins with dkong`

Also, `[arcade]` can be used to provide default settings for all arcade cores.

**Comment by birdybro** [comment]
Thanks! Great point!

**Comment by tjanas** [comment]
Fixed via https://github.com/MiSTer-devel/MkDocs_MiSTer/commit/9cee7625a7ec18108968015023c3c350208ad51d
