### ISSUE TITLE
Altera download link does not resolve anymore

### ISSUE THREAD

**Issue by elaberge** [MiSTer-devel/MkDocs_MiSTer#57]
It seems like Intel dropped the download.altera.com links, documentation should be adjusted. Simply replacing "download.altera.com" by "downloads.intel.com" is enough (note "downloads" is now plural).

eg: the Windows link is now https://downloads.intel.com/akdlm/software/acdsinst/17.0std.2/602/ib_tar/Quartus-lite-17.0.2.602-windows.tar

**Comment by birdybro** [comment]
Good call! Fixing it now! Thanks!
